data/urls.py
from django.urls import path
from storeApp import views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'data'

urlpatterns = [
    path('spec/', views.spec_list, name='spec_list'),
    path('spec/<str:id>/', views.spec_detail, name='spec_detail'),
    path('spec//', views.invalid_spec, name='invalid_spec'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include(('storeApp.urls', 'storeApp'), namespace='storeApp')),
    path('', include(('data.urls', 'data'), namespace='data')),
    path('admin/', admin.site.urls),
] 

storeApp/urls.py
from django.urls import path
from storeApp import views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'storeApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('store/', views.store, name='store'),
] 

data/models.py
from django.db import models

# Create your models here.

storeApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    photo_of_product = models.ImageField(upload_to='products/')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_in_stock = models.IntegerField()
    category = models.ForeignKey('ProductCategory', on_delete=models.CASCADE)
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def clean(self):
        if self.price < 0:
            raise ValidationError({
                'price': 'Цена не может быть отрицательной. '
            })
        if self.quantity_in_stock < 0:
            raise ValidationError({
                'quantity_in_stock': 'Остаток не может быть отрицательным. '
            })


class Cart(models.Model):
    user = models.OneToOneField(User,  on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Корзина пользователя: {self.user.username}"

    def total_cost(self):
        return sum(item.item_cost() for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product.name} ({self.quantity} шт)"

    def item_cost(self):
        return self.product.price * self.quantity

    def clean(self):
        if self.quantity > self.product.quantity_in_stock:
            raise ValidationError('Количество товара в корзине не может превышать количество товара на складе.'
                                  )

data/views.py
from django.shortcuts import render
import json
import os

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseNotFound


def invalid_spec(request):
    return render(request, 'data/404.html', status=404)


def load_data():

    file_path = os.path.join(settings.BASE_DIR, 'data',
                             'fixtures', 'dump.json')
    with open(file_path, encoding='utf-8') as f:
        return json.load(f)


def spec_list(request):
    data = load_data()

    # фильтруем только квалификации
    specialties = [item for item in data if item['model']
                   == 'data.specialty']

    context = {
        'title': 'Квалификации',
        'specialties': specialties,
    }

    return render(request, 'data/spec_list.html', context)


def spec_detail(request, id):
    data = load_data()

    try:
        if not id:
            raise ValueError

        id = int(id)
        if id <= 0:
            raise ValueError
    except:
        return render(request, 'data/404.html', status=404)

    # Ищем квалификацию по id
    specialty = next(
        (item for item in data if item['model'] == 'data.specialty' and item['pk'] == id), None)

    if specialty is None:
        return render(request, 'data/404.html', status=404)

    context = {
        'specialty': specialty
    }

    return render(request, 'data/spec_detail.html', context)

storeApp/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'Главная',
    }
    return render(request, 'storeApp/index.html', context)


def about(request):
    context = {
        'title': 'Об авторе',
    }
    return render(request, 'storeApp/about.html', context)


def store(request):
    context = {
        'title': 'Магазин',
    }
    return render(request, 'storeApp/store.html', context)

data/templates/data/spec_detail.html
{% extends 'storeApp/layout.html' %}
{% load static %}

{% block content %}
  <div class="specialty-data">
    <h1 class="specialty-data__title">Информация о квалификации</h1>
    <div class="specialty-data__info">
      <p class="specialty-data__text">
        <strong>Код:</strong> {{ specialty.fields.code|default:'Нет данных' }}
      </p>
      <p class="specialty-data__text">
        <strong>Название:</strong> {{ specialty.fields.title|default:'Нет данных' }}
      </p>
      <p class="specialty-data__text">
        <strong>Тип квалификации:</strong> {{ specialty.fields.c_type|default:'Нет данных' }}
      </p>
      <p class="specialty-data__text">
        <strong>Группа:</strong> {{ specialty.fields.group|default:'Нет данных' }}
      </p>
      <p class="specialty-data__text">
        <strong>Предшествующие квалификации:</strong> {{ specialty.fields.prev|default:'Нет данных' }}
      </p>
      <p class="specialty-data__text">
        <strong>Описание:</strong> {{ specialty.fields.desc|default:'Нет данных' }}
      </p>
    </div>

    <a class="specialty-data__link" href="{% url 'storeApp:index' %}">← Главная</a>
  </div>
{% endblock %}

data/templates/data/spec_list.html
{% extends 'storeApp/layout.html' %}
{% load static %}


{% block content %}
<div class="specialties">
  <h1 class="specialties__title">
    Список квалификаций
  </h1>
  <ul class="specialties__list">
    {% for spec in specialties %}
    <li class="specialties__list-item">
      <strong> {{ spec.fields.code}} </strong> - {{ spec.fields.title}} <em> {{spec.fields.c_type }} </em>
    </li>
    {% endfor %}
  </ul>
  <a class="specialties__link" href="{% url 'storeApp:index' %}"> ← Главная</a>
</div>
{% endblock content %}

storeApp/templates/storeApp/about.html
{% extends 'storeApp/layout.html' %}
{% load static %}



{% block content%}
<header>
  <div class="container">
    <div class="header__inner">
      <h1 class="header__title">
        Программист из 81 ТП? <span> МГКЦТешник</span>
      </h1>
    </div>
  </div>
</header>
<main>
  <div class="container">
    <div class="main__inner">
      <h2 class="main__title">
        Кучерина Стефания Андреевна
      </h2>
      <ul class="main__info">
        <li class="main__info-item">
          <p class="main__info-text">
            <span>Группа:</span> 81ТП
          </p>
        </li>
        <li class="main__info-item">
          <p class="main__info-text">
            <span>Курс:</span> 2
          </p>
        </li>
        <li class="main__info-item">
          <p class="main__info-text">
            <span>Куратор:</span> Кохно Тамара Аркадьевна
          </p>
        </li>
      </ul>
      <div class="main__box">
        <img class="main__box-image" src="{% static 'deps/images/about-page.jpg' %}" alt="Eren Jeger" width="300px" loading="lazy">
      </div>
      <a class="tohome-link" href="{% url 'storeApp:index' %}"> ← Главная</a>
    </div>
  </div>
</main>
{% endblock %}

storeApp/templates/storeApp/index.html
{% extends 'storeApp/layout.html' %}

{% block content %}
  <main>
    <div class="container">
      <div class="links">
        <a class="about-link" href="{% url 'storeApp:about' %}">Об авторе</a>
        <a class="store-link" href="{% url 'storeApp:store' %}">О магазине</a>
      </div>

      <aside class="sidebar">
        <h2 class="sidebar__title">Лабораторная №15</h2>
        <nav class="sidebar__spec">
          <a class="sidebar__spec-link" href="{% url 'data:spec_list' %}">Список квалификаций</a>
          <form method="get" action="{% url 'data:spec_detail' 0 %}" onsubmit="this.action = '/spec/' + this.id.value + '/'">
            <label for="spec-id">Введите ID квалификации:</label>
            <input type="number" id="spec-id" name="id" min="1" required />
            <button type="submit">Найти</button>
          </form>
        </nav>
      </aside>
    </div>
  </main>
{% endblock %}

storeApp/templates/storeApp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}">
  <link rel="icon" href="{% static 'deps/images/favoicon.png' %}" type="image/x-icon">

  <title>{{ title }}</title>
</head>

<body>
  {% block content%}
  {% endblock %}
</body>

</html>

storeApp/templates/storeApp/store.html
{% extends 'storeApp/layout.html' %}
{% load static %}



{% block content %}
<header class="store">
  <div class="container">
    <div class="header__store-inner">
      <div class="header__image">
        <a class="header__image-link" href="#">
          <img src="{% static 'deps/images/header-image.png' %}" alt="Robinzon" width="80px" loading="lazy">
        </a>
      </div>
      <h1 class="header__store-title"><span>Only yours </span> Robinzon </h1>
    </div>
  </div>
</header>
<main>
  <div class="container">
    <div class="main__store-inner">
      <p class="main__text">
        Магазин туристического снаряжения от Robinzon.
        Лучшее качество <span>только у нас</span>
      </p>
      <div class="main__phone">
        <h2 class="main__phone-title">
          Всегда рады помочь!
        </h2>
        <ul class="main__number-list">
          <li class="main__phone-mtc">
            <img src="{% static 'deps/images/mtc.png' %}" alt="MTC logo" width="10px" loading="lazy">
            <p class="main__phone-text">
              +375 (29) 545-60-70
            </p>
          </li>
          <li class="main__phone-a1">
            <img src="{% static 'deps/images/A1.jpg' %}" alt="A1 logo" width="15px" loading="lazy">
            <p class="main__phone-text">
              +375 (29) 602-60-70
            </p>
          </li>
          <li class="main__phone-mtc --special">
            <img src="{% static 'deps/images/A1.jpg' %}" alt="A1 logo" width="15px" loading="lazy">
            <p class="main__phone-text">
              +375 (29) 602-55-70
              <span>юр. лицо</span>
            </p>
          </li>
        </ul>
      </div>
      <p class="main__address">
        ТЦ Немига, <span>этаж 0, место 28</span>
      </p>

      <a class="tohome-link" href="{% url 'storeApp:index' %}">← Главная</a>
    </div>
  </div>
</main>

{% endblock content%}